test_author_can_update_comment (tests.CommentPermissionsTest.test_author_can_update_comment) ... ok
test_author_can_update_issue (tests.CommentPermissionsTest.test_author_can_update_issue) ... ok
test_author_can_update_project (tests.CommentPermissionsTest.test_author_can_update_project) ... FAIL
test_cannot_create_user_with_age_under_15 (tests.CommentPermissionsTest.test_cannot_create_user_with_age_under_15) ... ok
test_contributor_can_list_issues (tests.CommentPermissionsTest.test_contributor_can_list_issues) ... ERROR
test_contributor_can_see_comment (tests.CommentPermissionsTest.test_contributor_can_see_comment) ... ok
test_contributor_can_view_project (tests.CommentPermissionsTest.test_contributor_can_view_project) ... FAIL
test_contributor_can_view_specific_issue (tests.CommentPermissionsTest.test_contributor_can_view_specific_issue) ... FAIL
test_contributor_cannot_update_comment (tests.CommentPermissionsTest.test_contributor_cannot_update_comment) ... ok
test_contributor_cannot_update_project (tests.CommentPermissionsTest.test_contributor_cannot_update_project) ... ok
test_stranger_cannot_see_comment (tests.CommentPermissionsTest.test_stranger_cannot_see_comment) ... FAIL
test_stranger_cannot_view_project (tests.CommentPermissionsTest.test_stranger_cannot_view_project) ... ok

======================================================================
ERROR: test_contributor_can_list_issues (tests.CommentPermissionsTest.test_contributor_can_list_issues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 111, in test_contributor_can_list_issues
    self.assertTrue(any(issue['id'] == str(self.issue.id) for issue in response.data))
                    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 111, in <genexpr>
    self.assertTrue(any(issue['id'] == str(self.issue.id) for issue in response.data))
                        ~~~~~^^^^^^
TypeError: string indices must be integers, not 'str'

======================================================================
FAIL: test_author_can_update_project (tests.CommentPermissionsTest.test_author_can_update_project)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 137, in test_author_can_update_project
    self.assertEqual(response.status_code, 200)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 403 != 200

======================================================================
FAIL: test_contributor_can_view_project (tests.CommentPermissionsTest.test_contributor_can_view_project)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 124, in test_contributor_can_view_project
    self.assertEqual(response.status_code, 200)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 403 != 200

======================================================================
FAIL: test_contributor_can_view_specific_issue (tests.CommentPermissionsTest.test_contributor_can_view_specific_issue)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 118, in test_contributor_can_view_specific_issue
    self.assertEqual(response.data['id'], str(self.issue.id))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 15 != '15'

======================================================================
FAIL: test_stranger_cannot_see_comment (tests.CommentPermissionsTest.test_stranger_cannot_see_comment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 58, in test_stranger_cannot_see_comment
    self.assertEqual(response.status_code, 403)  # Non-contributeur = pas d'acc√®s
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 404 != 403

----------------------------------------------------------------------
Ran 12 tests in 16.875s

FAILED (failures=4, errors=1)


Rapport de couverture:
Name                                 Stmts   Miss  Cover
--------------------------------------------------------
rest\urls.py                             6      0   100%
support_api\migrations\__init__.py       0      0   100%
support_api\permissions.py              45     12    73%
support_api\serializers.py              60     10    83%
support_api\tests.py                   103      2    98%
support_api\urls.py                     10      0   100%
support_api\views.py                    71     24    66%
--------------------------------------------------------
TOTAL                                  295     48    84%
