test_author_can_update_comment (tests.CommentPermissionsTest.test_author_can_update_comment) ... ok
test_contributor_can_see_comment (tests.CommentPermissionsTest.test_contributor_can_see_comment) ... ok
test_contributor_cannot_update_comment (tests.CommentPermissionsTest.test_contributor_cannot_update_comment) ... ok
test_stranger_cannot_see_comment (tests.CommentPermissionsTest.test_stranger_cannot_see_comment) ... ok
test_author_can_update_issue (tests.IssuePermissionsTest.test_author_can_update_issue) ... ok
test_contributor_can_list_issues (tests.IssuePermissionsTest.test_contributor_can_list_issues) ... ok
test_contributor_can_view_specific_issue (tests.IssuePermissionsTest.test_contributor_can_view_specific_issue) ... ok
test_author_can_update_project (tests.ProjectPermissionsTest.test_author_can_update_project) ... FAIL
test_contributor_can_view_project (tests.ProjectPermissionsTest.test_contributor_can_view_project) ... FAIL
test_contributor_cannot_update_project (tests.ProjectPermissionsTest.test_contributor_cannot_update_project) ... ok
test_stranger_cannot_view_project (tests.ProjectPermissionsTest.test_stranger_cannot_view_project) ... ok
test_cannot_create_user_with_age_under_15 (tests.UserCreationTest.test_cannot_create_user_with_age_under_15) ... ok

======================================================================
FAIL: test_author_can_update_project (tests.ProjectPermissionsTest.test_author_can_update_project)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 165, in test_author_can_update_project
    self.assertEqual(response.status_code, 200)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 403 != 200

======================================================================
FAIL: test_contributor_can_view_project (tests.ProjectPermissionsTest.test_contributor_can_view_project)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\RESTFUL\support_api\tests.py", line 150, in test_contributor_can_view_project
    self.assertEqual(response.status_code, 200)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 403 != 200

----------------------------------------------------------------------
Ran 12 tests in 16.955s

FAILED (failures=2)


Rapport de couverture:
Name                                 Stmts   Miss  Cover
--------------------------------------------------------
rest\urls.py                             6      0   100%
support_api\migrations\__init__.py       0      0   100%
support_api\permissions.py              45     14    69%
support_api\serializers.py              60     10    83%
support_api\tests.py                   121      2    98%
support_api\urls.py                     10      0   100%
support_api\views.py                    75     26    65%
--------------------------------------------------------
TOTAL                                  317     52    84%
